# Specifying this is necessary as kubeadm init is run explicitly without setting up kube-proxy and as a
# consequence, although it exports KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT with a
# ClusterIP of the kube-apiserver service to the environment, there is no kube-proxy in our setup
# provisioning that service. The Cilium agent therefore needs to be made aware of this information through
# below configuration.
# https://docs.cilium.io/en/stable/gettingstarted/kubeproxy-free/
k8sServiceHost: "10.172.50.30"
k8sServicePort: 6443

bpf:
  # -- Enable native IP masquerade support in eBPF
  masquerade: true

  # -- Configure whether direct routing mode should route traffic via
  # host stack (true) or directly and more efficiently out of BPF (false) if
  # the kernel supports it. The latter has the implication that it will also
  # bypass netfilter in the host namespace.
  hostRouting: false

# -- Configure container runtime specific integration.
containerRuntime:
  # -- Enables specific integrations for container runtimes.
  # Supported values:
  # - containerd
  # - crio
  # - docker
  # - none
  # - auto (automatically detect the container runtime)
  integration: crio
  # -- Configure the path to the container runtime control socket.
  socketPath: "unix:///var/run/crio/crio.sock"

ipam:
  # -- Configure IP Address Management mode.
  # ref: https://docs.cilium.io/en/stable/concepts/networking/ipam/
  mode: "cluster-pool"
  operator:
    # -- Deprecated in favor of ipam.operator.clusterPoolIPv4PodCIDRList.
    # IPv4 CIDR range to delegate to individual nodes for IPAM.
    #clusterPoolIPv4PodCIDR: "10.142.0.0/16"
    # -- IPv4 CIDR list range to delegate to individual nodes for IPAM.
    clusterPoolIPv4PodCIDRList: ["10.142.0.0/16"]
    # -- IPv4 CIDR mask size to delegate to individual nodes for IPAM.
    clusterPoolIPv4MaskSize: 23

# -- Configure the kube-proxy replacement in Cilium BPF datapath
# Valid options are "disabled", "probe", "partial", "strict".
# ref: https://docs.cilium.io/en/stable/gettingstarted/kubeproxy-free/
kubeProxyReplacement: "strict"
